# Generated by Django 6.0.2 on 2026-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petrequest_age_petrequest_gender_petrequest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Reunited', 'Reunited')], default='Pending', max_length=10),
        ),
    ]
