# Generated by Django 6.0.2 on 2026-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrequest',
            name='age_unit',
            field=models.CharField(choices=[('Months', 'Months'), ('Years', 'Years')], default='Years', max_length=10),
        ),
        migrations.AddField(
            model_name='petrequest',
            name='is_verified_vet',
            field=models.BooleanField(default=False),
        ),
    ]
