# Generated by Django 6.0.2 on 2026-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petrequest_age_unit_petrequest_is_verified_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrequest',
            name='pet_type',
            field=models.CharField(choices=[('Bird', 'Bird'), ('Cat', 'Cat'), ('Chinchilla', 'Chinchilla'), ('Dog', 'Dog'), ('Ferret', 'Ferret'), ('Gerbil', 'Gerbil'), ('Guinea Pig', 'Guinea Pig'), ('Hamster', 'Hamster'), ('Mouse', 'Mouse'), ('Rabbit', 'Rabbit'), ('Reptile', 'Reptile'), ('Other', 'Other')], max_length=20),
        ),
    ]
