# Generated by Django 6.0.2 on 2026-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_reportabuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportabuse',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reportabuse',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
