# Generated by Django 6.0.2 on 2026-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_reportabuse_image_url_reportabuse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrequest',
            name='request_type',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Adoption', 'Adoption')], max_length=10),
        ),
    ]
