# Generated by Django 6.0.2 on 2026-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_petrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrequest',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Couple/Both', 'Couple/Both')], max_length=15),
        ),
    ]
