# Generated by Django 6.0.2 on 2026-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_petcontactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcontactrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='petrequest',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='List any known medical illnesses or diseases.', null=True),
        ),
        migrations.AddField(
            model_name='petrequest',
            name='vaccination_status',
            field=models.CharField(blank=True, choices=[('Fully Vaccinated', 'Fully Vaccinated'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Not Vaccinated', 'Not Vaccinated'), ('Unknown', 'Unknown')], max_length=30, null=True),
        ),
    ]
