# Generated by Django 5.2.11 on 2026-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_petcontactrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True),
        ),
    ]
