# Generated by Django 6.0.2 on 2026-03-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_petrequest_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportabuse',
            name='image_url',
        ),
        migrations.AddField(
            model_name='reportabuse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abuse_reports/'),
        ),
        migrations.AlterField(
            model_name='reportabuse',
            name='pet_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='pets.petrequest'),
        ),
    ]
