# Generated by Django 6.0.2 on 2026-03-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_remove_reportabuse_image_url_reportabuse_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pet_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pets.petrequest'),
        ),
    ]
