# Generated by Django 6.0.2 on 2026-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_city_profile_preferred_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code string to give to staff members', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can still be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
